plugins {
    id 'java'
    id 'jacoco'
    id 'me.champeau.jmh' version '0.7.2'
}

group = 'customtreeset'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

jacoco {
    toolVersion = "0.8.11"
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.openjfx:javafx-graphics:21:mac'

    compileOnly("org.projectlombok:lombok:1.18.46")
    annotationProcessor("org.projectlombok:lombok:1.18.46")

    testCompileOnly("org.projectlombok:lombok:1.18.46")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.46")
    testImplementation 'org.assertj:assertj-core:3.25.3'
    jmhImplementation 'org.openjdk.jmh:jmh-core:1.37'
    jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    finalizedBy jacocoTestCoverageVerification
    reports {
        xml.required = true
        csv.required = false
        html.required = true
    }
}

def benchmarkExclusions = [
        '**/*PerformanceTest*.class',
        '**/*Benchmark*.class'
]

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(
                files(classDirectories.files.collect { dir ->
                    fileTree(dir: dir).exclude(benchmarkExclusions)
                })
        )
    }
}

check {
    dependsOn jacocoTestCoverageVerification
}

jmh {
    includes = ['.*']
    fork = 1
    warmupIterations = 3
    iterations = 5
    resultFormat = 'CSV'
}